name: projekt_konrad_klima_pam
description: "Projekt zaliczeniowy PAM - Konrad Klima."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.6.0
  provider: ^6.1.5+1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  cached_network_image: ^3.4.1
  google_fonts: ^6.3.2
  firebase_core: ^4.2.1
  firebase_crashlytics: ^5.0.5
  firebase_analytics: ^12.0.4
  shimmer: ^3.0.0
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  build_runner: ^2.4.13
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
